version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=Atm
      - MYSQL_PASSWORD=root1234
    network_mode: "service:atm-development"
    #ports:
    #  - 3306:3306
  atm-development:
    image: atm
    ports:
      - 8080:8080
    #  - 3306
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=root1234
      - DATABASE_NAME=Atm
      - DATABASE_PORT=3306
      - DATABASE_USER=root
